<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>beauty_center_main_window</name>
    <message>
        <location filename="../ui/views/main_window.ui" line="124"/>
        <source> APPOINTMENTS</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../ui/views/main_window.ui" line="152"/>
        <source> CLIENTS</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../ui/views/main_window.ui" line="180"/>
        <source> TREATMENTS</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../ui/views/main_window.ui" line="224"/>
        <source> SETTINGS</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../ui/views/main_window.ui" line="256"/>
        <source>TextLabel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../ui/views/main_window.ui" line="268"/>
        <source>about:blank</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../ui/views/main_window.ui" line="280"/>
        <source>PushButton</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>main</name>
    <message>
        <location filename="../main.py" line="34"/>
        <source>DEBUG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="35"/>
        <source>INFO</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="36"/>
        <source>WARNING</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="37"/>
        <source>CRITICAL</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="38"/>
        <source>FATAL</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="41"/>
        <source>UNKNOWN</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="61"/>
        <source>Deleted old executable: {old_path}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="68"/>
        <source>Old executable not found: {old_path}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="73"/>
        <source>Failed to delete old executable: {old_path}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="87"/>
        <location filename="../main.py" line="118"/>
        <location filename="../main.py" line="336"/>
        <location filename="../main.py" line="397"/>
        <location filename="../main.py" line="428"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="87"/>
        <source>Failed to copy new executable:
{source_path}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="93"/>
        <source>Copied new executable: {target_path}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="109"/>
        <source>Stopped and running new executable: {exe_path}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="118"/>
        <source>Failed to stop and run new executable:
{exe_path}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="133"/>
        <source>Executable path is correct: {current_exe_path}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="142"/>
        <source>Incorrect Executable Path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="143"/>
        <source>The executable has been moved in other dir:
Expected: {expected_path}
Found: {current_exe_path}

The correct path will now be restored.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="163"/>
        <source>Executable name is correct: {current_name}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="172"/>
        <source>Incorrect Executable Name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="173"/>
        <source>The executable has been renamed:
Expected: {expected_name}
Found: {current_name}

The correct name will now be restored.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="191"/>
        <source>Connection quality is good: {latency} ms</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="197"/>
        <source>Connection quality is bad, unable to check new version: {latency} ms</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="203"/>
        <source>Failed to check connection quality, unable to check new version: {exception}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="219"/>
        <source>Failed to check for latest release: {api_url} Error: {exception}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="240"/>
        <source>No new version found.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="247"/>
        <source>New Version Available</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="249"/>
        <source>A new version is available:
Local version: {curr_ver}
Remote version: {latest_ver}

Download now?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="255"/>
        <source>Download cancelled.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="259"/>
        <source>Downloading latest version...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="270"/>
        <source>Failed to get download URL for latest release.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="275"/>
        <source>Downloading latest version {display_name} from ({download_url})</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="285"/>
        <source>Downloading latest version {display_name} to ({out_path})</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="307"/>
        <source>Failed to download latest version:
{exception}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="314"/>
        <source>Downloaded latest version {display_name} to ({out_path})</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="337"/>
        <source>Failed to start local server:
{instance_server_name}
Error: {error}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="369"/>
        <source>Loaded Italian translation.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="373"/>
        <source>Italian translation not found. Use default English translation.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="398"/>
        <source>Unexpected positional argument(s) found:
{positional_args}.
Use --help or -h for usage information.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="428"/>
        <source>Another instance of {app_name} is already running.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="441"/>
        <source>Loaded style {file_name}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../main.py" line="444"/>
        <source>Failed to load style {file_name}</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
